import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Kanit } from "next/font/google";

const kanit = Kanit({
    weight: "400",
    subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={`${kanit.className} antialiased`}>
                    <Providers>
                        <Navbar />
                        <main className="container">{children}</main>
                    </Providers>
                </body>
            </html>
        </ClerkProvider>
    );
}
